use std::fs;
use std::process::Command;

use tracing::{error, info};

struct InstallParams {
    board_id: String,
    board_name: String,
    api_url: String,
    api_key: String,
    output_backend: String,
    width: u32,
    height: u32,
}

fn read_install_params() -> Result<InstallParams, String> {
    let board_id = std::env::var("BOARD_ID")
        .map_err(|_| "BOARD_ID env var is required".to_string())?;
    let server_url = std::env::var("SERVER_URL")
        .map_err(|_| "SERVER_URL env var is required".to_string())?;

    // Strip trailing slashes and any path — we only want the origin (scheme + host + port)
    let server_url = server_url.trim_end_matches('/').to_string();
    let origin = match server_url.find("://") {
        Some(i) => {
            let after_scheme = &server_url[i + 3..];
            let host_end = after_scheme.find('/').map(|j| i + 3 + j).unwrap_or(server_url.len());
            &server_url[..host_end]
        }
        None => &server_url,
    };
    let api_url = origin
        .replace("https://", "wss://")
        .replace("http://", "ws://")
        + "/ws/agent";

    Ok(InstallParams {
        board_name: std::env::var("BOARD_NAME").unwrap_or_else(|_| board_id.clone()),
        api_key: std::env::var("API_KEY").unwrap_or_default(),
        output_backend: std::env::var("OUTPUT_BACKEND")
            .unwrap_or_else(|_| "framebuffer".into()),
        width: std::env::var("WIDTH")
            .ok()
            .and_then(|v| v.parse().ok())
            .unwrap_or(1920),
        height: std::env::var("HEIGHT")
            .ok()
            .and_then(|v| v.parse().ok())
            .unwrap_or(1080),
        board_id,
        api_url,
    })
}

fn render_config_toml(p: &InstallParams) -> String {
    use serde::Serialize;

    #[derive(Serialize)]
    struct ConfigFile<'a> {
        board_id: &'a str,
        board_name: &'a str,
        api_url: &'a str,
        api_key: &'a str,
        output_backend: &'a str,
        width: u32,
        height: u32,
        fullscreen: bool,
        player_socket: &'a str,
        cache_dir: &'a str,
        report_interval_secs: u64,
        screenshot_interval_secs: u64,
        player_restart_delay_secs: u64,
    }

    let cfg = ConfigFile {
        board_id: &p.board_id,
        board_name: &p.board_name,
        api_url: &p.api_url,
        api_key: &p.api_key,
        output_backend: &p.output_backend,
        width: p.width,
        height: p.height,
        fullscreen: true,
        player_socket: "/run/veha/player.sock",
        cache_dir: "/var/cache/veha",
        report_interval_secs: 10,
        screenshot_interval_secs: 60,
        player_restart_delay_secs: 5,
    };

    let mut out = String::from("# Generated by veha-edge install — edit as needed\n\n");
    out.push_str(&toml::to_string(&cfg).expect("failed to serialize config"));
    out
}

fn render_systemd_unit() -> String {
    r#"[Unit]
Description=veha-edge board agent + player
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/opt/veha/veha-edge run
Restart=on-failure
RestartSec=5
Environment=RUST_LOG=info

[Install]
WantedBy=multi-user.target
"#
    .into()
}

fn render_tmpfiles_conf() -> String {
    "d /run/veha 0755 root root -\n".into()
}

pub fn run() {
    let params = match read_install_params() {
        Ok(p) => p,
        Err(e) => {
            error!("{e}");
            std::process::exit(1);
        }
    };

    info!("Installing veha-edge for board_id={}", params.board_id);

    // 1. Copy binary to /opt/veha/
    let exe = std::env::current_exe().expect("cannot resolve current exe path");
    fs::create_dir_all("/opt/veha").expect("failed to create /opt/veha");
    fs::copy(&exe, "/opt/veha/veha-edge").expect("failed to copy binary to /opt/veha/veha-edge");
    info!("Binary installed to /opt/veha/veha-edge");

    // 2. Write config
    fs::create_dir_all("/etc/veha").expect("failed to create /etc/veha");
    fs::write("/etc/veha/veha-edge.toml", render_config_toml(&params))
        .expect("failed to write /etc/veha/veha-edge.toml");
    // Restrict to root-only read: config contains api_key
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(
            "/etc/veha/veha-edge.toml",
            std::fs::Permissions::from_mode(0o600),
        )
        .expect("failed to secure config permissions");
    }
    info!("Config written to /etc/veha/veha-edge.toml");

    // 3. Create cache dir
    fs::create_dir_all("/var/cache/veha").expect("failed to create /var/cache/veha");

    // 4. Write tmpfiles.d entry (creates /run/veha on boot)
    fs::write("/etc/tmpfiles.d/veha.conf", render_tmpfiles_conf())
        .expect("failed to write tmpfiles.d config");
    // Also create the run dir now so we don't need a reboot
    fs::create_dir_all("/run/veha").ok();

    // 5. Write systemd unit
    fs::write(
        "/etc/systemd/system/veha-edge.service",
        render_systemd_unit(),
    )
    .expect("failed to write systemd unit");
    info!("Systemd unit written");

    // 6. Enable and start
    for args in [
        vec!["daemon-reload"],
        vec!["enable", "--now", "veha-edge"],
    ] {
        let status = Command::new("systemctl")
            .args(&args)
            .status()
            .expect("failed to run systemctl");
        if !status.success() {
            error!("systemctl {} failed", args.join(" "));
            std::process::exit(1);
        }
    }

    println!("\nveha-edge installed and started successfully.");
    println!("  Board ID : {}", params.board_id);
    println!("  API URL  : {}", params.api_url);
    println!("\nCheck logs: journalctl -u veha-edge -f");
}

pub fn uninstall(purge: bool) {
    info!("Uninstalling veha-edge");

    Command::new("systemctl")
        .args(["disable", "--now", "veha-edge"])
        .status()
        .ok();

    let paths = [
        "/etc/systemd/system/veha-edge.service",
        "/etc/tmpfiles.d/veha.conf",
        "/etc/veha/veha-edge.toml",
        "/opt/veha/veha-edge",
    ];
    for path in &paths {
        fs::remove_file(path).ok();
    }
    fs::remove_dir("/etc/veha").ok();
    fs::remove_dir("/opt/veha").ok();
    fs::remove_dir("/run/veha").ok();

    if purge {
        fs::remove_dir_all("/var/cache/veha").ok();
        info!("Media cache removed");
    }

    Command::new("systemctl").arg("daemon-reload").status().ok();

    println!("veha-edge uninstalled.");
    if !purge {
        println!("Media cache kept at /var/cache/veha. Use --purge to remove it.");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_config_toml() {
        let params = InstallParams {
            board_id: "board-001".into(),
            board_name: "Lobby".into(),
            api_url: "ws://192.168.1.17:3000/ws/agent".into(),
            api_key: "".into(),
            output_backend: "framebuffer".into(),
            width: 1920,
            height: 1080,
        };
        let toml_str = render_config_toml(&params);
        assert!(toml_str.contains("board_id"));
        assert!(toml_str.contains("board-001"));
        assert!(toml_str.contains("ws://192.168.1.17:3000/ws/agent"));
        assert!(toml_str.contains("framebuffer"));
        // Verify it parses back as valid TOML
        let parsed: toml::Value = toml::from_str(&toml_str).expect("rendered TOML must be valid");
        assert_eq!(parsed["board_id"].as_str().unwrap(), "board-001");
    }

    #[test]
    fn test_render_systemd_unit() {
        let unit = render_systemd_unit();
        assert!(unit.contains("ExecStart=/opt/veha/veha-edge run"));
        assert!(unit.contains("Restart=on-failure"));
        assert!(unit.contains("WantedBy=multi-user.target"));
    }

    #[test]
    fn test_env_missing_board_id() {
        // SAFETY: single-threaded test run (--test-threads=1)
        unsafe {
            std::env::remove_var("BOARD_ID");
            std::env::remove_var("SERVER_URL");
        }
        let result = read_install_params();
        assert!(result.is_err());
    }

    #[test]
    fn test_api_url_derivation() {
        // SAFETY: single-threaded test run (--test-threads=1)
        unsafe {
            std::env::set_var("SERVER_URL", "http://192.168.1.17:3000");
            std::env::set_var("BOARD_ID", "test");
        }
        let params = read_install_params().unwrap();
        assert_eq!(params.api_url, "ws://192.168.1.17:3000/ws/agent");
    }

    #[test]
    fn test_api_url_trailing_slash() {
        // SAFETY: single-threaded test run (--test-threads=1)
        unsafe {
            std::env::set_var("SERVER_URL", "http://192.168.1.17:3000/");
            std::env::set_var("BOARD_ID", "test");
        }
        let params = read_install_params().unwrap();
        assert_eq!(params.api_url, "ws://192.168.1.17:3000/ws/agent");
    }
}
